**1)** Responde Verdadero o Falso

    a- Los vectores se pueden describir en base a su módulo y dirección
    b- Los vectores se pueden describir en base a sus componentes cartesianos
    c- Dos vectores pueden tener misma dirección pero distinto sentido
    d- Dos vectores no pueden tener mismo módulo pero direcciones distintas

In [1]:
print('a) ', True)

print('b) ', True)

print('c) ', True)

print('d) ', False)

a)  True
b)  True
c)  True
d)  False


**2)** ¿Cuál es el módulo de los siguientes vectores?

    a- (3,4)    = 5
    b- (1,1)    = 1
    c- (10,10)  = 
    d- (-3,-4)

In [3]:
print('a) ', 5)

print('b) ', 1)

print('c) ', 200**(1/2))

print('d) ', 5)

a)  5
b)  1
c)  14.142135623730951
d)  5


**3)** Resolver las siguientes multiplicaciones de vectores por escalares

    a- (1,1) * 3
    b- (12,15) * 1/3
    c- (10,1) * 10
    d- (4,5) * 5

In [4]:
print('a) (3,3)')

print('b) (4,5)')

print('c) (100,10)')

print('d) (20,25)')

a) (3,3)
b) (4,5)
c) (100,10)
d) (20,25)


**4)** Responder Verdadero o Falso

    a- El producto escalar de dos vectores obtiene multiplicando entre sí la norma de cada vector y el coseno del ángulo que se forma entre ellos.
    b- El producto escalar siempre da como resultado un escalar.
    c- El producto vectorial da como resultado otro vector.
    d- Si dos vectores son paralelos, el angulo entre ellos es 90 grados.

In [5]:
print('a) ', True)

print('b) ', True)

print('c) ', True)

print('d) ', False)

a)  True
b)  True
c)  True
d)  False


**5)** ¿Que dimensiones tienen las siguientes matrices?

    a- 5 filas y 7 columnas
    b- 2 columnas y 9 filas
    c- 3 filas y 3 columnas

In [6]:
print('a) 5x7')

print('a) 9x2')

print('a) 3x3')

a) 5x7
a) 9x2
a) 3x3


**6)** Responder con Si/No si es posible realizar las siguientes operaciones entre matrices:

    a- (3 x 4) + (1 x 2)    No
    b- (1 x 1) + (1 x 1)    Sí
    c- (8 x 8) - (1 x 1)    No
    d- (4 x 2) - (2 x 3)    Sí
    d- (4 x 2) * (2 x 3)    Sí

**7)** Realizar la multiplicación entre las siguientes matrices:

a-
![unaImagenConBoxShadow](../_src/assets/ejercicios/producto1.png)

b-
![unaImagenConBoxShadow](../_src/assets/ejercicios/producto2.png)

c-
![unaImagenConBoxShadow](../_src/assets/ejercicios/producto3.png)

d-
![unaImagenConBoxShadow](../_src/assets/ejercicios/producto4.png)

e-
![unaImagenConBoxShadow](../_src/assets/ejercicios/producto5.png)


In [4]:
import numpy as np

a1 = np.array([[2],[-1]])
a2 = np.array([[3,5]])
A = np.dot(a1,a2)
b1 = np.array([[2,0],[1,3]])
b2 = np.array([[-1,-1],[5,6]])
B = np.dot(b1,b2)
c1 = np.array([[1,4,7],[2,5,8],[3,6,9]])
c2 = np.array([[1,-1,2],[2,-1,2],[3,-3,0]])
C = np.dot(c1,c2)
d1 = np.array([[3,0,0],[0,2,0],[0,0,1]])
d2 = np.array([[1,0,0],[0,-1,0],[0,0,-7]])
D = np.dot(d1,d2)
e1 = np.array([[1,2],[-1,0],[-3,-1]])
e2 = np.array([[2,0,1],[-5,2,3]])
E = np.dot(e1,e2)

print(f' Primera \n {A}  \n Segunda \n {B} \n Tercera \n {C} \n Cuarta \n {D} \n Quinta \n {E} ')


 Primera 
 [[ 6 10]
 [-3 -5]]  
 Segunda 
 [[-2 -2]
 [14 17]] 
 Tercera 
 [[ 30 -26  10]
 [ 36 -31  14]
 [ 42 -36  18]] 
 Cuarta 
 [[ 3  0  0]
 [ 0 -2  0]
 [ 0  0 -7]] 
 Quinta 
 [[-8  4  7]
 [-2  0 -1]
 [-1 -2 -6]] 


**7)** Realizar la multiplicación entre las siguientes matrices:

a-
![unaImagenConBoxShadow](../_src/assets/ejercicios/producto1.png)
<br>
![unaImagenConBoxShadow](../_src/assets/ejercicios/producto1_sol.png)
<br>
<br>
b-
![unaImagenConBoxShadow](../_src/assets/ejercicios/producto2.png)
<br>
![unaImagenConBoxShadow](../_src/assets/ejercicios/producto2_sol.png)
<br>
<br>
c-
![unaImagenConBoxShadow](../_src/assets/ejercicios/producto3.png)
<br>
![unaImagenConBoxShadow](../_src/assets/ejercicios/producto3_sol.png)
<br>
<br>
d-
![unaImagenConBoxShadow](../_src/assets/ejercicios/producto4.png)
<br>
![unaImagenConBoxShadow](../_src/assets/ejercicios/producto4_sol.png)
<br>
<br>
e-
![unaImagenConBoxShadow](../_src/assets/ejercicios/producto5.png)
<br>
![unaImagenConBoxShadow](../_src/assets/ejercicios/producto5_sol.png)
<br>
<br>